version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-2019
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"    
    ports:
      - "1434:1433"

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssqltools
    depends_on:
      - sqlserver
    volumes:
      - ./docs/sql/sql-server/init.sql:/tmp/init.sql
      - ./docs/sql/sql-server/init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh

  # app:
  #   container_name: app-golang
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #     - 8082:8082  
  #   volumes:
  #     - .:/go/src/
