version: '3.9'

services:

  app:
    container_name: app-golang
    build:
      dockerfile: Dockerfile
      context: .      
      # target: dev
    ports:
      - 8080:8080      
    volumes:
      - .:/go/src/